spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

        - id: user-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthFilter

        - id: user-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/doctor/**
          filters:
            - AuthFilter

        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/api/v1/auth/**

        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/api/v1/account/**
          filters:
            - AuthFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
