server:
  port: 9003

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthcare_db
    username: root
    password: 10021051
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: healthcare-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  services:
    patient: http://localhost:9001/api/v1/patient