server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: 10021051
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  cookie-name: "JWT"

jwt:
  secretKey: "eDr/NgGRj2RRo1xRw6+EYfGUqbG424KYCgZ0vPIt/qWkfAgy8sl9dysxOaDyBmho"
  valid-duration: 3600
  refreshable-duration: 36000
