server:
  port: 9002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/service_management_db
    username: root
    password: 10021051
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: service-management

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka