server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: 10021051
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka