server:
  port: 9006

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appointment_db
    username: root
    password: 101051
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: appointment-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka