spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**, /api/v1/account/**
          filters:
            - AuthFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/doctor/**, /api/v1/patient/**
          filters:
            - AuthFilter

        - id: schedule-service
          uri: lb://SCHEDULE-SERVICE
          predicates:
            - Path=/api/v1/room/**, /api/v1/schedule/**, /api/v1/shift/**, /api/v1/specialty/**
          filters:
            - AuthFilter

        - id: healthcare-service
          uri: lb://HEALTHCARE-SERVICE
          predicates:
            - Path=/api/v1/appointment/**, /api/v1/diagnosis/**, /api/v1/medication/**, /api/v1/supply/**, /api/v1/prescription/**, /api/v1/symptom/**, /api/v1/test/**
          filters:
            - AuthFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka